io:
    output_dir: output/gaussian_field_inference/4src_bin_128_25slabs_sys
    
slabs:
    chi_min: 0.
    chi_max: 4000.
    slab_width: 150.
    N_grid: 128
    L: 250. 
    
observables:
    bin0:
        type: dens 
        nz_file: data/des_y3/nz/redmagic_bin1.npy
        
    bin1:
        type: dens
        nz_file: data/des_y3/nz/redmagic_bin2.npy
     
    bin2:
        type: dens
        nz_file: data/des_y3/nz/redmagic_bin3.npy
        
    bin3:
        type: dens
        nz_file: data/des_y3/nz/redmagic_bin4.npy
    
    bin4:
        type: dens
        nz_file: data/des_y3/nz/redmagic_bin5.npy
        
    bin5:
        type: kappa
        nz_file: data/des_y3/nz/source_bin1.npy
        
    bin6:
        type: kappa
        nz_file: data/des_y3/nz/source_bin2.npy
        
    bin7:
        type: kappa
        nz_file: data/des_y3/nz/source_bin3.npy
        
    bin8:
        type: kappa
        nz_file: data/des_y3/nz/source_bin4.npy
        
    
sampling:  
    parameter_blocking:
        sample_cosmo: True
        sample_src_pars: True
        sample_ia: True
        sample_lens_pars: False
    mcmc:
        n_warmup: 500
        n_samples: 1000
